package com.modelo;
// Generated 27/08/2011 09:10:57 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Lugar generated by hbm2java
 */
public class Lugar  implements java.io.Serializable {


     private int codigo;
     private Lugar lugar;
     private String nombre;
     private String tipo;
     private Set<Persona> personasForCiudadDomicilio = new HashSet<Persona>(0);
     private Set<Persona> personasForLugarNacimiento = new HashSet<Persona>(0);
     private Set<Lugar> lugars = new HashSet<Lugar>(0);

    public Lugar() {
    }

	
    public Lugar(int codigo, String nombre, String tipo) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.tipo = tipo;
    }
    public Lugar(int codigo, Lugar lugar, String nombre, String tipo, Set<Persona> personasForCiudadDomicilio, Set<Persona> personasForLugarNacimiento, Set<Lugar> lugars) {
       this.codigo = codigo;
       this.lugar = lugar;
       this.nombre = nombre;
       this.tipo = tipo;
       this.personasForCiudadDomicilio = personasForCiudadDomicilio;
       this.personasForLugarNacimiento = personasForLugarNacimiento;
       this.lugars = lugars;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Lugar getLugar() {
        return this.lugar;
    }
    
    public void setLugar(Lugar lugar) {
        this.lugar = lugar;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Persona> getPersonasForCiudadDomicilio() {
        return this.personasForCiudadDomicilio;
    }
    
    public void setPersonasForCiudadDomicilio(Set<Persona> personasForCiudadDomicilio) {
        this.personasForCiudadDomicilio = personasForCiudadDomicilio;
    }
    public Set<Persona> getPersonasForLugarNacimiento() {
        return this.personasForLugarNacimiento;
    }
    
    public void setPersonasForLugarNacimiento(Set<Persona> personasForLugarNacimiento) {
        this.personasForLugarNacimiento = personasForLugarNacimiento;
    }
    public Set<Lugar> getLugars() {
        return this.lugars;
    }
    
    public void setLugars(Set<Lugar> lugars) {
        this.lugars = lugars;
    }




}


