package com.modelo;
// Generated 27/08/2011 09:10:57 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int codigoRol;
     private String descripcion;
     private Set<RolPersona> rolPersonas = new HashSet<RolPersona>(0);

    public Rol() {
    }

	
    public Rol(int codigoRol, String descripcion) {
        this.codigoRol = codigoRol;
        this.descripcion = descripcion;
    }
    public Rol(int codigoRol, String descripcion, Set<RolPersona> rolPersonas) {
       this.codigoRol = codigoRol;
       this.descripcion = descripcion;
       this.rolPersonas = rolPersonas;
    }
   
    public int getCodigoRol() {
        return this.codigoRol;
    }
    
    public void setCodigoRol(int codigoRol) {
        this.codigoRol = codigoRol;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<RolPersona> getRolPersonas() {
        return this.rolPersonas;
    }
    
    public void setRolPersonas(Set<RolPersona> rolPersonas) {
        this.rolPersonas = rolPersonas;
    }




}


