package com.modelo;
// Generated 27/08/2011 09:10:57 AM by Hibernate Tools 3.2.1.GA



/**
 * RolPersona generated by hbm2java
 */
public class RolPersona  implements java.io.Serializable {


     private RolPersonaId id;
     private Rol rol;
     private Persona persona;
     private Institucion institucion;

    public RolPersona() {
    }

    public RolPersona(RolPersonaId id, Rol rol, Persona persona, Institucion institucion) {
       this.id = id;
       this.rol = rol;
       this.persona = persona;
       this.institucion = institucion;
    }
   
    public RolPersonaId getId() {
        return this.id;
    }
    
    public void setId(RolPersonaId id) {
        this.id = id;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Institucion getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(Institucion institucion) {
        this.institucion = institucion;
    }




}


