package com.modelo;
// Generated 27/08/2011 09:10:57 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String codigoRegistro;
     private Persona persona;
     private Lugar lugarByLugarNacimiento;
     private Lugar lugarByCiudadDomicilio;
     private Date fechaRegistro;
     private String tipoDocumento;
     private String dni;
     private String nombres;
     private String primerApellido;
     private String segundoApellido;
     private int lugarExpedicion;
     private Date fechaExpedicion;
     private String genero;
     private Date fechaNacimiento;
     private String direccion;
     private String telefono;
     private Integer estrato;
     private String fotoE;
     private String rh;
     private Integer nivelSisben;
     private String apellidoAcudiente;
     private String dirAcudiente;
     private String telAcudiente;
     private String correoElectronico;
     private String tituloProfesional;
     private String usuario;
     private String password;
     private Set<RolPersona> rolPersonas = new HashSet<RolPersona>(0);
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Persona() {
    }

	
    public Persona(String codigoRegistro, Lugar lugarByCiudadDomicilio, Date fechaRegistro, String tipoDocumento, String dni, String nombres, String primerApellido, int lugarExpedicion, Date fechaExpedicion, String genero, String direccion, String telefono) {
        this.codigoRegistro = codigoRegistro;
        this.lugarByCiudadDomicilio = lugarByCiudadDomicilio;
        this.fechaRegistro = fechaRegistro;
        this.tipoDocumento = tipoDocumento;
        this.dni = dni;
        this.nombres = nombres;
        this.primerApellido = primerApellido;
        this.lugarExpedicion = lugarExpedicion;
        this.fechaExpedicion = fechaExpedicion;
        this.genero = genero;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Persona(String codigoRegistro, Persona persona, Lugar lugarByLugarNacimiento, Lugar lugarByCiudadDomicilio, Date fechaRegistro, String tipoDocumento, String dni, String nombres, String primerApellido, String segundoApellido, int lugarExpedicion, Date fechaExpedicion, String genero, Date fechaNacimiento, String direccion, String telefono, Integer estrato, String fotoE, String rh, Integer nivelSisben, String apellidoAcudiente, String dirAcudiente, String telAcudiente, String correoElectronico, String tituloProfesional, String usuario, String password, Set<RolPersona> rolPersonas, Set<Persona> personas) {
       this.codigoRegistro = codigoRegistro;
       this.persona = persona;
       this.lugarByLugarNacimiento = lugarByLugarNacimiento;
       this.lugarByCiudadDomicilio = lugarByCiudadDomicilio;
       this.fechaRegistro = fechaRegistro;
       this.tipoDocumento = tipoDocumento;
       this.dni = dni;
       this.nombres = nombres;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.lugarExpedicion = lugarExpedicion;
       this.fechaExpedicion = fechaExpedicion;
       this.genero = genero;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.telefono = telefono;
       this.estrato = estrato;
       this.fotoE = fotoE;
       this.rh = rh;
       this.nivelSisben = nivelSisben;
       this.apellidoAcudiente = apellidoAcudiente;
       this.dirAcudiente = dirAcudiente;
       this.telAcudiente = telAcudiente;
       this.correoElectronico = correoElectronico;
       this.tituloProfesional = tituloProfesional;
       this.usuario = usuario;
       this.password = password;
       this.rolPersonas = rolPersonas;
       this.personas = personas;
    }
   
    public String getCodigoRegistro() {
        return this.codigoRegistro;
    }
    
    public void setCodigoRegistro(String codigoRegistro) {
        this.codigoRegistro = codigoRegistro;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Lugar getLugarByLugarNacimiento() {
        return this.lugarByLugarNacimiento;
    }
    
    public void setLugarByLugarNacimiento(Lugar lugarByLugarNacimiento) {
        this.lugarByLugarNacimiento = lugarByLugarNacimiento;
    }
    public Lugar getLugarByCiudadDomicilio() {
        return this.lugarByCiudadDomicilio;
    }
    
    public void setLugarByCiudadDomicilio(Lugar lugarByCiudadDomicilio) {
        this.lugarByCiudadDomicilio = lugarByCiudadDomicilio;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public int getLugarExpedicion() {
        return this.lugarExpedicion;
    }
    
    public void setLugarExpedicion(int lugarExpedicion) {
        this.lugarExpedicion = lugarExpedicion;
    }
    public Date getFechaExpedicion() {
        return this.fechaExpedicion;
    }
    
    public void setFechaExpedicion(Date fechaExpedicion) {
        this.fechaExpedicion = fechaExpedicion;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Integer getEstrato() {
        return this.estrato;
    }
    
    public void setEstrato(Integer estrato) {
        this.estrato = estrato;
    }
    public String getFotoE() {
        return this.fotoE;
    }
    
    public void setFotoE(String fotoE) {
        this.fotoE = fotoE;
    }
    public String getRh() {
        return this.rh;
    }
    
    public void setRh(String rh) {
        this.rh = rh;
    }
    public Integer getNivelSisben() {
        return this.nivelSisben;
    }
    
    public void setNivelSisben(Integer nivelSisben) {
        this.nivelSisben = nivelSisben;
    }
    public String getApellidoAcudiente() {
        return this.apellidoAcudiente;
    }
    
    public void setApellidoAcudiente(String apellidoAcudiente) {
        this.apellidoAcudiente = apellidoAcudiente;
    }
    public String getDirAcudiente() {
        return this.dirAcudiente;
    }
    
    public void setDirAcudiente(String dirAcudiente) {
        this.dirAcudiente = dirAcudiente;
    }
    public String getTelAcudiente() {
        return this.telAcudiente;
    }
    
    public void setTelAcudiente(String telAcudiente) {
        this.telAcudiente = telAcudiente;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getTituloProfesional() {
        return this.tituloProfesional;
    }
    
    public void setTituloProfesional(String tituloProfesional) {
        this.tituloProfesional = tituloProfesional;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<RolPersona> getRolPersonas() {
        return this.rolPersonas;
    }
    
    public void setRolPersonas(Set<RolPersona> rolPersonas) {
        this.rolPersonas = rolPersonas;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


