package com.modelo;
// Generated 27/08/2011 09:10:57 AM by Hibernate Tools 3.2.1.GA



/**
 * RolPersonaId generated by hbm2java
 */
public class RolPersonaId  implements java.io.Serializable {


     private int institucion;
     private int rol;
     private String persona;

    public RolPersonaId() {
    }

    public RolPersonaId(int institucion, int rol, String persona) {
       this.institucion = institucion;
       this.rol = rol;
       this.persona = persona;
    }
   
    public int getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(int institucion) {
        this.institucion = institucion;
    }
    public int getRol() {
        return this.rol;
    }
    
    public void setRol(int rol) {
        this.rol = rol;
    }
    public String getPersona() {
        return this.persona;
    }
    
    public void setPersona(String persona) {
        this.persona = persona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolPersonaId) ) return false;
		 RolPersonaId castOther = ( RolPersonaId ) other; 
         
		 return (this.getInstitucion()==castOther.getInstitucion())
 && (this.getRol()==castOther.getRol())
 && ( (this.getPersona()==castOther.getPersona()) || ( this.getPersona()!=null && castOther.getPersona()!=null && this.getPersona().equals(castOther.getPersona()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInstitucion();
         result = 37 * result + this.getRol();
         result = 37 * result + ( getPersona() == null ? 0 : this.getPersona().hashCode() );
         return result;
   }   


}


