package com.modelo;
// Generated 27/08/2011 09:10:57 AM by Hibernate Tools 3.2.1.GA



/**
 * Sede generated by hbm2java
 */
public class Sede  implements java.io.Serializable {


     private int codigo;
     private Institucion institucion;
     private String nombre;
     private String direccion;
     private String telefono;
     private Character estado;
     private String ciudad;

    public Sede() {
    }

	
    public Sede(int codigo, Institucion institucion, String nombre, String direccion, String telefono, String ciudad) {
        this.codigo = codigo;
        this.institucion = institucion;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
        this.ciudad = ciudad;
    }
    public Sede(int codigo, Institucion institucion, String nombre, String direccion, String telefono, Character estado, String ciudad) {
       this.codigo = codigo;
       this.institucion = institucion;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.estado = estado;
       this.ciudad = ciudad;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Institucion getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(Institucion institucion) {
        this.institucion = institucion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }




}


